#!/bin/bash

# 将主目录所有者改成系统创建的用户
permissionFile=${SMARTDNS_HOME}/.permission.lock
if [ "${SET_PERMISSIONS}" = true ] && [ ! -f "${permissionFile}" ]; then
  chown -R "${USERNAME}":"${USERNAME}" "${SMARTDNS_HOME}"

  if [ ! -f "${permissionFile}" ]; then
    su-exec "${USERNAME}" touch "${permissionFile}"
  fi
fi
